name: voucher_creator
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0-36.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  pdf: ^3.10.4
  permission_handler: ^10.4.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.2.0
  syncfusion_flutter_pdfviewer: ^22.2.8
  syncfusion_flutter_signaturepad: ^22.2.8
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  path_provider: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  open_filex: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/image/icon.png"
  android: true

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/image/
